### ISSUE TITLE
pretained model

### ISSUE THREAD

**Issue by lqsunshine** [felixkreuk/HideAndSpeak#1]
I'm interested in your work and want to follow it. If you can provide pre-training models and audio sample(the link is valid) , I can directly test your samples. Thanks

**Comment by felixkreuk** [comment]
Hi @lqsunshine, glad to know you find our work interesting!
Apologies, the audio samples site seems to be down, I re-uploaded it. You can now find it [here](https://felixkreuk.github.io/projects/steg/).
Regarding pre-trained models, unfortunately I no longer have access to the cluster I used for training. I will try to recover them and let you know. In any case, it should be pretty straightforward to train this model on your own data (or any public audio dataset really).

Good luck!

**Comment by lqsunshine** [comment]
> Hi @lqsunshine, glad to know you find our work interesting! Apologies, the audio samples site seems to be down, I re-uploaded it. You can now find it [here](https://felixkreuk.github.io/projects/steg/). Regarding pre-trained models, unfortunately I no longer have access to the cluster I used for training. I will try to recover them and let you know. In any case, it should be pretty straightforward to train this model on your own data (or any public audio dataset really).
> 
> Good luck!

thanks！
